// 本文件为生成的代码，所有修改都会丢失
using System;
using System.Collections.Generic;
public partial class MsgMeta
{
    public MsgMeta()
    {
        data = new[]
        {
            new MsgMetaData(MsgCmdId.Result, Result.Parser, false),
            new MsgMetaData(MsgCmdId.Ping, Ping.Parser, false),
            new MsgMetaData(MsgCmdId.Pong, Pong.Parser, true),
            new MsgMetaData(MsgCmdId.NPlayer, NPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.NSocialPlayer, NSocialPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.NMaterialItem, NMaterialItem.Parser, false),
            new MsgMetaData(MsgCmdId.NCurrencyItem, NCurrencyItem.Parser, false),
            new MsgMetaData(MsgCmdId.NWeaponItem, NWeaponItem.Parser, false),
            new MsgMetaData(MsgCmdId.NDiscItem, NDiscItem.Parser, false),
            new MsgMetaData(MsgCmdId.NFloat3, NFloat3.Parser, false),
            new MsgMetaData(MsgCmdId.NPosRot, NPosRot.Parser, false),
            new MsgMetaData(MsgCmdId.NWeaponAttr, NWeaponAttr.Parser, false),
            new MsgMetaData(MsgCmdId.NDiscAttr, NDiscAttr.Parser, false),
            new MsgMetaData(MsgCmdId.MsgGachaWeapon, MsgGachaWeapon.Parser, false),
            new MsgMetaData(MsgCmdId.MsgGachaDisc, MsgGachaDisc.Parser, false),
            new MsgMetaData(MsgCmdId.ReqRegister, ReqRegister.Parser, false),
            new MsgMetaData(MsgCmdId.RspRegister, RspRegister.Parser, true),
            new MsgMetaData(MsgCmdId.ReqLogin, ReqLogin.Parser, false),
            new MsgMetaData(MsgCmdId.RspLogin, RspLogin.Parser, true),
            new MsgMetaData(MsgCmdId.ReqGetPlayerData, ReqGetPlayerData.Parser, false),
            new MsgMetaData(MsgCmdId.RspGetPlayerData, RspGetPlayerData.Parser, true),
            new MsgMetaData(MsgCmdId.NSyncRole, NSyncRole.Parser, false),
            new MsgMetaData(MsgCmdId.NSyncPlayer, NSyncPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.NSimRole, NSimRole.Parser, false),
            new MsgMetaData(MsgCmdId.NSimPlayer, NSimPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.MsgEnterRoom, MsgEnterRoom.Parser, false),
            new MsgMetaData(MsgCmdId.MsgUpdateFromAutonomous, MsgUpdateFromAutonomous.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyUpdateFromAuthority, NotifyUpdateFromAuthority.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyAddSimulatedPlayers, NotifyAddSimulatedPlayers.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyRemoveSimulatedPlayers, NotifyRemoveSimulatedPlayers.Parser, false),
            new MsgMetaData(MsgCmdId.MsgRolePlayAction, MsgRolePlayAction.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyOtherRolePlayAction, NotifyOtherRolePlayAction.Parser, false),
            new MsgMetaData(MsgCmdId.MsgSwitchRole, MsgSwitchRole.Parser, false),
            new MsgMetaData(MsgCmdId.ReqGetExchangeItems, ReqGetExchangeItems.Parser, false),
            new MsgMetaData(MsgCmdId.RspGetExchangeItems, RspGetExchangeItems.Parser, true),
            new MsgMetaData(MsgCmdId.NExchangeItem, NExchangeItem.Parser, false),
            new MsgMetaData(MsgCmdId.ReqExchange, ReqExchange.Parser, false),
            new MsgMetaData(MsgCmdId.RspExchange, RspExchange.Parser, true),
            new MsgMetaData(MsgCmdId.ReqSearchPlayer, ReqSearchPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.RspSearchPlayer, RspSearchPlayer.Parser, true),
            new MsgMetaData(MsgCmdId.ReqSendAddFriend, ReqSendAddFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspSendAddFriend, RspSendAddFriend.Parser, true),
            new MsgMetaData(MsgCmdId.ReqAcceptAddFriend, ReqAcceptAddFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspAcceptAddFriend, RspAcceptAddFriend.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRefuseAddFriend, ReqRefuseAddFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspRefuseAddFriend, RspRefuseAddFriend.Parser, true),
            new MsgMetaData(MsgCmdId.ReqDeleteFriend, ReqDeleteFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspDeleteFriend, RspDeleteFriend.Parser, true),
            new MsgMetaData(MsgCmdId.ReqModifySignature, ReqModifySignature.Parser, false),
            new MsgMetaData(MsgCmdId.RspModifySignature, RspModifySignature.Parser, true),
            new MsgMetaData(MsgCmdId.ReqModifyPassword, ReqModifyPassword.Parser, false),
            new MsgMetaData(MsgCmdId.RspModifyPassword, RspModifyPassword.Parser, true),
            new MsgMetaData(MsgCmdId.ReqModifyAvatar, ReqModifyAvatar.Parser, false),
            new MsgMetaData(MsgCmdId.RspModifyAvatar, RspModifyAvatar.Parser, true),
            new MsgMetaData(MsgCmdId.NChatMsg, NChatMsg.Parser, false),
            new MsgMetaData(MsgCmdId.ReqSendChatMsg, ReqSendChatMsg.Parser, false),
            new MsgMetaData(MsgCmdId.RspSendChatMsg, RspSendChatMsg.Parser, true),
            new MsgMetaData(MsgCmdId.NotifyReceiveChatMsg, NotifyReceiveChatMsg.Parser, false),
            new MsgMetaData(MsgCmdId.NRole, NRole.Parser, false),
            new MsgMetaData(MsgCmdId.ReqRoleRemoveDisc, ReqRoleRemoveDisc.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleRemoveDisc, RspRoleRemoveDisc.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRoleEquipDisc, ReqRoleEquipDisc.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleEquipDisc, RspRoleEquipDisc.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRoleRemoveWeapon, ReqRoleRemoveWeapon.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleRemoveWeapon, RspRoleRemoveWeapon.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRoleEquipWeapon, ReqRoleEquipWeapon.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleEquipWeapon, RspRoleEquipWeapon.Parser, true),
            new MsgMetaData(MsgCmdId.NotifySpawnMonster, NotifySpawnMonster.Parser, false),
            new MsgMetaData(MsgCmdId.MsgMonsterTakeDamage, MsgMonsterTakeDamage.Parser, false),
            new MsgMetaData(MsgCmdId.NotifySyncMonsterTakeDamage, NotifySyncMonsterTakeDamage.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyMonsterDie, NotifyMonsterDie.Parser, false),
            new MsgMetaData(MsgCmdId.ReqStartQuest, ReqStartQuest.Parser, false),
            new MsgMetaData(MsgCmdId.RspStartQuest, RspStartQuest.Parser, true),
            new MsgMetaData(MsgCmdId.ReqUpgradeDisc, ReqUpgradeDisc.Parser, false),
            new MsgMetaData(MsgCmdId.RspUpgradeDisc, RspUpgradeDisc.Parser, true),
            new MsgMetaData(MsgCmdId.MsgGatherMaterial, MsgGatherMaterial.Parser, false),
            new MsgMetaData(MsgCmdId.MsgCompleteQuestChain, MsgCompleteQuestChain.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyObtainItems, NotifyObtainItems.Parser, false),
        };
    
        cmdIdToData = new Dictionary<uint, MsgMetaData>
        {
            {MsgCmdId.Result, data[0]},
            {MsgCmdId.Ping, data[1]},
            {MsgCmdId.Pong, data[2]},
            {MsgCmdId.NPlayer, data[3]},
            {MsgCmdId.NSocialPlayer, data[4]},
            {MsgCmdId.NMaterialItem, data[5]},
            {MsgCmdId.NCurrencyItem, data[6]},
            {MsgCmdId.NWeaponItem, data[7]},
            {MsgCmdId.NDiscItem, data[8]},
            {MsgCmdId.NFloat3, data[9]},
            {MsgCmdId.NPosRot, data[10]},
            {MsgCmdId.NWeaponAttr, data[11]},
            {MsgCmdId.NDiscAttr, data[12]},
            {MsgCmdId.MsgGachaWeapon, data[13]},
            {MsgCmdId.MsgGachaDisc, data[14]},
            {MsgCmdId.ReqRegister, data[15]},
            {MsgCmdId.RspRegister, data[16]},
            {MsgCmdId.ReqLogin, data[17]},
            {MsgCmdId.RspLogin, data[18]},
            {MsgCmdId.ReqGetPlayerData, data[19]},
            {MsgCmdId.RspGetPlayerData, data[20]},
            {MsgCmdId.NSyncRole, data[21]},
            {MsgCmdId.NSyncPlayer, data[22]},
            {MsgCmdId.NSimRole, data[23]},
            {MsgCmdId.NSimPlayer, data[24]},
            {MsgCmdId.MsgEnterRoom, data[25]},
            {MsgCmdId.MsgUpdateFromAutonomous, data[26]},
            {MsgCmdId.NotifyUpdateFromAuthority, data[27]},
            {MsgCmdId.NotifyAddSimulatedPlayers, data[28]},
            {MsgCmdId.NotifyRemoveSimulatedPlayers, data[29]},
            {MsgCmdId.MsgRolePlayAction, data[30]},
            {MsgCmdId.NotifyOtherRolePlayAction, data[31]},
            {MsgCmdId.MsgSwitchRole, data[32]},
            {MsgCmdId.ReqGetExchangeItems, data[33]},
            {MsgCmdId.RspGetExchangeItems, data[34]},
            {MsgCmdId.NExchangeItem, data[35]},
            {MsgCmdId.ReqExchange, data[36]},
            {MsgCmdId.RspExchange, data[37]},
            {MsgCmdId.ReqSearchPlayer, data[38]},
            {MsgCmdId.RspSearchPlayer, data[39]},
            {MsgCmdId.ReqSendAddFriend, data[40]},
            {MsgCmdId.RspSendAddFriend, data[41]},
            {MsgCmdId.ReqAcceptAddFriend, data[42]},
            {MsgCmdId.RspAcceptAddFriend, data[43]},
            {MsgCmdId.ReqRefuseAddFriend, data[44]},
            {MsgCmdId.RspRefuseAddFriend, data[45]},
            {MsgCmdId.ReqDeleteFriend, data[46]},
            {MsgCmdId.RspDeleteFriend, data[47]},
            {MsgCmdId.ReqModifySignature, data[48]},
            {MsgCmdId.RspModifySignature, data[49]},
            {MsgCmdId.ReqModifyPassword, data[50]},
            {MsgCmdId.RspModifyPassword, data[51]},
            {MsgCmdId.ReqModifyAvatar, data[52]},
            {MsgCmdId.RspModifyAvatar, data[53]},
            {MsgCmdId.NChatMsg, data[54]},
            {MsgCmdId.ReqSendChatMsg, data[55]},
            {MsgCmdId.RspSendChatMsg, data[56]},
            {MsgCmdId.NotifyReceiveChatMsg, data[57]},
            {MsgCmdId.NRole, data[58]},
            {MsgCmdId.ReqRoleRemoveDisc, data[59]},
            {MsgCmdId.RspRoleRemoveDisc, data[60]},
            {MsgCmdId.ReqRoleEquipDisc, data[61]},
            {MsgCmdId.RspRoleEquipDisc, data[62]},
            {MsgCmdId.ReqRoleRemoveWeapon, data[63]},
            {MsgCmdId.RspRoleRemoveWeapon, data[64]},
            {MsgCmdId.ReqRoleEquipWeapon, data[65]},
            {MsgCmdId.RspRoleEquipWeapon, data[66]},
            {MsgCmdId.NotifySpawnMonster, data[67]},
            {MsgCmdId.MsgMonsterTakeDamage, data[68]},
            {MsgCmdId.NotifySyncMonsterTakeDamage, data[69]},
            {MsgCmdId.NotifyMonsterDie, data[70]},
            {MsgCmdId.ReqStartQuest, data[71]},
            {MsgCmdId.RspStartQuest, data[72]},
            {MsgCmdId.ReqUpgradeDisc, data[73]},
            {MsgCmdId.RspUpgradeDisc, data[74]},
            {MsgCmdId.MsgGatherMaterial, data[75]},
            {MsgCmdId.MsgCompleteQuestChain, data[76]},
            {MsgCmdId.NotifyObtainItems, data[77]},
        };

        typeToData = new Dictionary<Type, MsgMetaData>
        {
            {typeof(Result), data[0]},
            {typeof(Ping), data[1]},
            {typeof(Pong), data[2]},
            {typeof(NPlayer), data[3]},
            {typeof(NSocialPlayer), data[4]},
            {typeof(NMaterialItem), data[5]},
            {typeof(NCurrencyItem), data[6]},
            {typeof(NWeaponItem), data[7]},
            {typeof(NDiscItem), data[8]},
            {typeof(NFloat3), data[9]},
            {typeof(NPosRot), data[10]},
            {typeof(NWeaponAttr), data[11]},
            {typeof(NDiscAttr), data[12]},
            {typeof(MsgGachaWeapon), data[13]},
            {typeof(MsgGachaDisc), data[14]},
            {typeof(ReqRegister), data[15]},
            {typeof(RspRegister), data[16]},
            {typeof(ReqLogin), data[17]},
            {typeof(RspLogin), data[18]},
            {typeof(ReqGetPlayerData), data[19]},
            {typeof(RspGetPlayerData), data[20]},
            {typeof(NSyncRole), data[21]},
            {typeof(NSyncPlayer), data[22]},
            {typeof(NSimRole), data[23]},
            {typeof(NSimPlayer), data[24]},
            {typeof(MsgEnterRoom), data[25]},
            {typeof(MsgUpdateFromAutonomous), data[26]},
            {typeof(NotifyUpdateFromAuthority), data[27]},
            {typeof(NotifyAddSimulatedPlayers), data[28]},
            {typeof(NotifyRemoveSimulatedPlayers), data[29]},
            {typeof(MsgRolePlayAction), data[30]},
            {typeof(NotifyOtherRolePlayAction), data[31]},
            {typeof(MsgSwitchRole), data[32]},
            {typeof(ReqGetExchangeItems), data[33]},
            {typeof(RspGetExchangeItems), data[34]},
            {typeof(NExchangeItem), data[35]},
            {typeof(ReqExchange), data[36]},
            {typeof(RspExchange), data[37]},
            {typeof(ReqSearchPlayer), data[38]},
            {typeof(RspSearchPlayer), data[39]},
            {typeof(ReqSendAddFriend), data[40]},
            {typeof(RspSendAddFriend), data[41]},
            {typeof(ReqAcceptAddFriend), data[42]},
            {typeof(RspAcceptAddFriend), data[43]},
            {typeof(ReqRefuseAddFriend), data[44]},
            {typeof(RspRefuseAddFriend), data[45]},
            {typeof(ReqDeleteFriend), data[46]},
            {typeof(RspDeleteFriend), data[47]},
            {typeof(ReqModifySignature), data[48]},
            {typeof(RspModifySignature), data[49]},
            {typeof(ReqModifyPassword), data[50]},
            {typeof(RspModifyPassword), data[51]},
            {typeof(ReqModifyAvatar), data[52]},
            {typeof(RspModifyAvatar), data[53]},
            {typeof(NChatMsg), data[54]},
            {typeof(ReqSendChatMsg), data[55]},
            {typeof(RspSendChatMsg), data[56]},
            {typeof(NotifyReceiveChatMsg), data[57]},
            {typeof(NRole), data[58]},
            {typeof(ReqRoleRemoveDisc), data[59]},
            {typeof(RspRoleRemoveDisc), data[60]},
            {typeof(ReqRoleEquipDisc), data[61]},
            {typeof(RspRoleEquipDisc), data[62]},
            {typeof(ReqRoleRemoveWeapon), data[63]},
            {typeof(RspRoleRemoveWeapon), data[64]},
            {typeof(ReqRoleEquipWeapon), data[65]},
            {typeof(RspRoleEquipWeapon), data[66]},
            {typeof(NotifySpawnMonster), data[67]},
            {typeof(MsgMonsterTakeDamage), data[68]},
            {typeof(NotifySyncMonsterTakeDamage), data[69]},
            {typeof(NotifyMonsterDie), data[70]},
            {typeof(ReqStartQuest), data[71]},
            {typeof(RspStartQuest), data[72]},
            {typeof(ReqUpgradeDisc), data[73]},
            {typeof(RspUpgradeDisc), data[74]},
            {typeof(MsgGatherMaterial), data[75]},
            {typeof(MsgCompleteQuestChain), data[76]},
            {typeof(NotifyObtainItems), data[77]},
        };
    }
}