// 本文件为生成的代码，所有修改都会丢失
using System;
using System.Collections.Generic;
public partial class MsgMeta
{
    public MsgMeta()
    {
        data = new[]
        {
            new MsgMetaData(MsgCmdId.Result, Result.Parser, false),
            new MsgMetaData(MsgCmdId.Ping, Ping.Parser, false),
            new MsgMetaData(MsgCmdId.Pong, Pong.Parser, true),
            new MsgMetaData(MsgCmdId.NPlayer, NPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.NSocialPlayer, NSocialPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.NMaterialItem, NMaterialItem.Parser, false),
            new MsgMetaData(MsgCmdId.NCurrencyItem, NCurrencyItem.Parser, false),
            new MsgMetaData(MsgCmdId.NWeaponItem, NWeaponItem.Parser, false),
            new MsgMetaData(MsgCmdId.NDiscItem, NDiscItem.Parser, false),
            new MsgMetaData(MsgCmdId.NVector3, NVector3.Parser, false),
            new MsgMetaData(MsgCmdId.NMovement, NMovement.Parser, false),
            new MsgMetaData(MsgCmdId.NWeaponAttr, NWeaponAttr.Parser, false),
            new MsgMetaData(MsgCmdId.NDiscAttr, NDiscAttr.Parser, false),
            new MsgMetaData(MsgCmdId.MsgGachaWeapon, MsgGachaWeapon.Parser, false),
            new MsgMetaData(MsgCmdId.MsgGachaDisc, MsgGachaDisc.Parser, false),
            new MsgMetaData(MsgCmdId.ReqRegister, ReqRegister.Parser, false),
            new MsgMetaData(MsgCmdId.RspRegister, RspRegister.Parser, true),
            new MsgMetaData(MsgCmdId.ReqLogin, ReqLogin.Parser, false),
            new MsgMetaData(MsgCmdId.RspLogin, RspLogin.Parser, true),
            new MsgMetaData(MsgCmdId.ReqGetPlayerData, ReqGetPlayerData.Parser, false),
            new MsgMetaData(MsgCmdId.RspGetPlayerData, RspGetPlayerData.Parser, true),
            new MsgMetaData(MsgCmdId.NSyncRole, NSyncRole.Parser, false),
            new MsgMetaData(MsgCmdId.NSyncPlayer, NSyncPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.MsgEnterRoom, MsgEnterRoom.Parser, false),
            new MsgMetaData(MsgCmdId.MsgUpdateFromAutonomous, MsgUpdateFromAutonomous.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyUpdateFromAuthority, NotifyUpdateFromAuthority.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyRemoveSimulatedPlayers, NotifyRemoveSimulatedPlayers.Parser, false),
            new MsgMetaData(MsgCmdId.MsgRolePlayAction, MsgRolePlayAction.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyOtherRolePlayAction, NotifyOtherRolePlayAction.Parser, false),
            new MsgMetaData(MsgCmdId.MsgSwitchRole, MsgSwitchRole.Parser, false),
            new MsgMetaData(MsgCmdId.ReqGetExchangeItems, ReqGetExchangeItems.Parser, false),
            new MsgMetaData(MsgCmdId.RspGetExchangeItems, RspGetExchangeItems.Parser, true),
            new MsgMetaData(MsgCmdId.NExchangeItem, NExchangeItem.Parser, false),
            new MsgMetaData(MsgCmdId.ReqExchange, ReqExchange.Parser, false),
            new MsgMetaData(MsgCmdId.RspExchange, RspExchange.Parser, true),
            new MsgMetaData(MsgCmdId.ReqSearchPlayer, ReqSearchPlayer.Parser, false),
            new MsgMetaData(MsgCmdId.RspSearchPlayer, RspSearchPlayer.Parser, true),
            new MsgMetaData(MsgCmdId.ReqSendAddFriend, ReqSendAddFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspSendAddFriend, RspSendAddFriend.Parser, true),
            new MsgMetaData(MsgCmdId.NotifyFriendRequestsAdd, NotifyFriendRequestsAdd.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyFriendRequestsRemove, NotifyFriendRequestsRemove.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyFriendsAdd, NotifyFriendsAdd.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyFriendsRemove, NotifyFriendsRemove.Parser, false),
            new MsgMetaData(MsgCmdId.ReqAcceptAddFriend, ReqAcceptAddFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspAcceptAddFriend, RspAcceptAddFriend.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRefuseAddFriend, ReqRefuseAddFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspRefuseAddFriend, RspRefuseAddFriend.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRemoveFriend, ReqRemoveFriend.Parser, false),
            new MsgMetaData(MsgCmdId.RspRemoveFriend, RspRemoveFriend.Parser, true),
            new MsgMetaData(MsgCmdId.ReqModifySignature, ReqModifySignature.Parser, false),
            new MsgMetaData(MsgCmdId.RspModifySignature, RspModifySignature.Parser, true),
            new MsgMetaData(MsgCmdId.ReqModifyPassword, ReqModifyPassword.Parser, false),
            new MsgMetaData(MsgCmdId.RspModifyPassword, RspModifyPassword.Parser, true),
            new MsgMetaData(MsgCmdId.ReqModifyAvatar, ReqModifyAvatar.Parser, false),
            new MsgMetaData(MsgCmdId.RspModifyAvatar, RspModifyAvatar.Parser, true),
            new MsgMetaData(MsgCmdId.NChatMsg, NChatMsg.Parser, false),
            new MsgMetaData(MsgCmdId.ReqSendChatMsg, ReqSendChatMsg.Parser, false),
            new MsgMetaData(MsgCmdId.RspSendChatMsg, RspSendChatMsg.Parser, true),
            new MsgMetaData(MsgCmdId.NotifyReceiveChatMsg, NotifyReceiveChatMsg.Parser, false),
            new MsgMetaData(MsgCmdId.NRole, NRole.Parser, false),
            new MsgMetaData(MsgCmdId.ReqRoleRemoveDisc, ReqRoleRemoveDisc.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleRemoveDisc, RspRoleRemoveDisc.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRoleEquipDisc, ReqRoleEquipDisc.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleEquipDisc, RspRoleEquipDisc.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRoleRemoveWeapon, ReqRoleRemoveWeapon.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleRemoveWeapon, RspRoleRemoveWeapon.Parser, true),
            new MsgMetaData(MsgCmdId.ReqRoleEquipWeapon, ReqRoleEquipWeapon.Parser, false),
            new MsgMetaData(MsgCmdId.RspRoleEquipWeapon, RspRoleEquipWeapon.Parser, true),
            new MsgMetaData(MsgCmdId.NotifySpawnMonster, NotifySpawnMonster.Parser, false),
            new MsgMetaData(MsgCmdId.MsgMonsterTakeDamage, MsgMonsterTakeDamage.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyMonsterTakeDamage, NotifyMonsterTakeDamage.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyMonsterDie, NotifyMonsterDie.Parser, false),
            new MsgMetaData(MsgCmdId.NQuaternion, NQuaternion.Parser, false),
            new MsgMetaData(MsgCmdId.NSyncMonster, NSyncMonster.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyMonsterRepMovement, NotifyMonsterRepMovement.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyMonsterPlayAction, NotifyMonsterPlayAction.Parser, false),
            new MsgMetaData(MsgCmdId.ReqStartQuest, ReqStartQuest.Parser, false),
            new MsgMetaData(MsgCmdId.RspStartQuest, RspStartQuest.Parser, true),
            new MsgMetaData(MsgCmdId.ReqUpgradeDisc, ReqUpgradeDisc.Parser, false),
            new MsgMetaData(MsgCmdId.RspUpgradeDisc, RspUpgradeDisc.Parser, true),
            new MsgMetaData(MsgCmdId.MsgGatherMaterial, MsgGatherMaterial.Parser, false),
            new MsgMetaData(MsgCmdId.MsgCompleteQuestChain, MsgCompleteQuestChain.Parser, false),
            new MsgMetaData(MsgCmdId.NotifyObtainItems, NotifyObtainItems.Parser, false),
        };
    
        cmdIdToData = new Dictionary<uint, MsgMetaData>
        {
            {MsgCmdId.Result, data[0]},
            {MsgCmdId.Ping, data[1]},
            {MsgCmdId.Pong, data[2]},
            {MsgCmdId.NPlayer, data[3]},
            {MsgCmdId.NSocialPlayer, data[4]},
            {MsgCmdId.NMaterialItem, data[5]},
            {MsgCmdId.NCurrencyItem, data[6]},
            {MsgCmdId.NWeaponItem, data[7]},
            {MsgCmdId.NDiscItem, data[8]},
            {MsgCmdId.NVector3, data[9]},
            {MsgCmdId.NMovement, data[10]},
            {MsgCmdId.NWeaponAttr, data[11]},
            {MsgCmdId.NDiscAttr, data[12]},
            {MsgCmdId.MsgGachaWeapon, data[13]},
            {MsgCmdId.MsgGachaDisc, data[14]},
            {MsgCmdId.ReqRegister, data[15]},
            {MsgCmdId.RspRegister, data[16]},
            {MsgCmdId.ReqLogin, data[17]},
            {MsgCmdId.RspLogin, data[18]},
            {MsgCmdId.ReqGetPlayerData, data[19]},
            {MsgCmdId.RspGetPlayerData, data[20]},
            {MsgCmdId.NSyncRole, data[21]},
            {MsgCmdId.NSyncPlayer, data[22]},
            {MsgCmdId.MsgEnterRoom, data[23]},
            {MsgCmdId.MsgUpdateFromAutonomous, data[24]},
            {MsgCmdId.NotifyUpdateFromAuthority, data[25]},
            {MsgCmdId.NotifyRemoveSimulatedPlayers, data[26]},
            {MsgCmdId.MsgRolePlayAction, data[27]},
            {MsgCmdId.NotifyOtherRolePlayAction, data[28]},
            {MsgCmdId.MsgSwitchRole, data[29]},
            {MsgCmdId.ReqGetExchangeItems, data[30]},
            {MsgCmdId.RspGetExchangeItems, data[31]},
            {MsgCmdId.NExchangeItem, data[32]},
            {MsgCmdId.ReqExchange, data[33]},
            {MsgCmdId.RspExchange, data[34]},
            {MsgCmdId.ReqSearchPlayer, data[35]},
            {MsgCmdId.RspSearchPlayer, data[36]},
            {MsgCmdId.ReqSendAddFriend, data[37]},
            {MsgCmdId.RspSendAddFriend, data[38]},
            {MsgCmdId.NotifyFriendRequestsAdd, data[39]},
            {MsgCmdId.NotifyFriendRequestsRemove, data[40]},
            {MsgCmdId.NotifyFriendsAdd, data[41]},
            {MsgCmdId.NotifyFriendsRemove, data[42]},
            {MsgCmdId.ReqAcceptAddFriend, data[43]},
            {MsgCmdId.RspAcceptAddFriend, data[44]},
            {MsgCmdId.ReqRefuseAddFriend, data[45]},
            {MsgCmdId.RspRefuseAddFriend, data[46]},
            {MsgCmdId.ReqRemoveFriend, data[47]},
            {MsgCmdId.RspRemoveFriend, data[48]},
            {MsgCmdId.ReqModifySignature, data[49]},
            {MsgCmdId.RspModifySignature, data[50]},
            {MsgCmdId.ReqModifyPassword, data[51]},
            {MsgCmdId.RspModifyPassword, data[52]},
            {MsgCmdId.ReqModifyAvatar, data[53]},
            {MsgCmdId.RspModifyAvatar, data[54]},
            {MsgCmdId.NChatMsg, data[55]},
            {MsgCmdId.ReqSendChatMsg, data[56]},
            {MsgCmdId.RspSendChatMsg, data[57]},
            {MsgCmdId.NotifyReceiveChatMsg, data[58]},
            {MsgCmdId.NRole, data[59]},
            {MsgCmdId.ReqRoleRemoveDisc, data[60]},
            {MsgCmdId.RspRoleRemoveDisc, data[61]},
            {MsgCmdId.ReqRoleEquipDisc, data[62]},
            {MsgCmdId.RspRoleEquipDisc, data[63]},
            {MsgCmdId.ReqRoleRemoveWeapon, data[64]},
            {MsgCmdId.RspRoleRemoveWeapon, data[65]},
            {MsgCmdId.ReqRoleEquipWeapon, data[66]},
            {MsgCmdId.RspRoleEquipWeapon, data[67]},
            {MsgCmdId.NotifySpawnMonster, data[68]},
            {MsgCmdId.MsgMonsterTakeDamage, data[69]},
            {MsgCmdId.NotifyMonsterTakeDamage, data[70]},
            {MsgCmdId.NotifyMonsterDie, data[71]},
            {MsgCmdId.NQuaternion, data[72]},
            {MsgCmdId.NSyncMonster, data[73]},
            {MsgCmdId.NotifyMonsterRepMovement, data[74]},
            {MsgCmdId.NotifyMonsterPlayAction, data[75]},
            {MsgCmdId.ReqStartQuest, data[76]},
            {MsgCmdId.RspStartQuest, data[77]},
            {MsgCmdId.ReqUpgradeDisc, data[78]},
            {MsgCmdId.RspUpgradeDisc, data[79]},
            {MsgCmdId.MsgGatherMaterial, data[80]},
            {MsgCmdId.MsgCompleteQuestChain, data[81]},
            {MsgCmdId.NotifyObtainItems, data[82]},
        };

        typeToData = new Dictionary<Type, MsgMetaData>
        {
            {typeof(Result), data[0]},
            {typeof(Ping), data[1]},
            {typeof(Pong), data[2]},
            {typeof(NPlayer), data[3]},
            {typeof(NSocialPlayer), data[4]},
            {typeof(NMaterialItem), data[5]},
            {typeof(NCurrencyItem), data[6]},
            {typeof(NWeaponItem), data[7]},
            {typeof(NDiscItem), data[8]},
            {typeof(NVector3), data[9]},
            {typeof(NMovement), data[10]},
            {typeof(NWeaponAttr), data[11]},
            {typeof(NDiscAttr), data[12]},
            {typeof(MsgGachaWeapon), data[13]},
            {typeof(MsgGachaDisc), data[14]},
            {typeof(ReqRegister), data[15]},
            {typeof(RspRegister), data[16]},
            {typeof(ReqLogin), data[17]},
            {typeof(RspLogin), data[18]},
            {typeof(ReqGetPlayerData), data[19]},
            {typeof(RspGetPlayerData), data[20]},
            {typeof(NSyncRole), data[21]},
            {typeof(NSyncPlayer), data[22]},
            {typeof(MsgEnterRoom), data[23]},
            {typeof(MsgUpdateFromAutonomous), data[24]},
            {typeof(NotifyUpdateFromAuthority), data[25]},
            {typeof(NotifyRemoveSimulatedPlayers), data[26]},
            {typeof(MsgRolePlayAction), data[27]},
            {typeof(NotifyOtherRolePlayAction), data[28]},
            {typeof(MsgSwitchRole), data[29]},
            {typeof(ReqGetExchangeItems), data[30]},
            {typeof(RspGetExchangeItems), data[31]},
            {typeof(NExchangeItem), data[32]},
            {typeof(ReqExchange), data[33]},
            {typeof(RspExchange), data[34]},
            {typeof(ReqSearchPlayer), data[35]},
            {typeof(RspSearchPlayer), data[36]},
            {typeof(ReqSendAddFriend), data[37]},
            {typeof(RspSendAddFriend), data[38]},
            {typeof(NotifyFriendRequestsAdd), data[39]},
            {typeof(NotifyFriendRequestsRemove), data[40]},
            {typeof(NotifyFriendsAdd), data[41]},
            {typeof(NotifyFriendsRemove), data[42]},
            {typeof(ReqAcceptAddFriend), data[43]},
            {typeof(RspAcceptAddFriend), data[44]},
            {typeof(ReqRefuseAddFriend), data[45]},
            {typeof(RspRefuseAddFriend), data[46]},
            {typeof(ReqRemoveFriend), data[47]},
            {typeof(RspRemoveFriend), data[48]},
            {typeof(ReqModifySignature), data[49]},
            {typeof(RspModifySignature), data[50]},
            {typeof(ReqModifyPassword), data[51]},
            {typeof(RspModifyPassword), data[52]},
            {typeof(ReqModifyAvatar), data[53]},
            {typeof(RspModifyAvatar), data[54]},
            {typeof(NChatMsg), data[55]},
            {typeof(ReqSendChatMsg), data[56]},
            {typeof(RspSendChatMsg), data[57]},
            {typeof(NotifyReceiveChatMsg), data[58]},
            {typeof(NRole), data[59]},
            {typeof(ReqRoleRemoveDisc), data[60]},
            {typeof(RspRoleRemoveDisc), data[61]},
            {typeof(ReqRoleEquipDisc), data[62]},
            {typeof(RspRoleEquipDisc), data[63]},
            {typeof(ReqRoleRemoveWeapon), data[64]},
            {typeof(RspRoleRemoveWeapon), data[65]},
            {typeof(ReqRoleEquipWeapon), data[66]},
            {typeof(RspRoleEquipWeapon), data[67]},
            {typeof(NotifySpawnMonster), data[68]},
            {typeof(MsgMonsterTakeDamage), data[69]},
            {typeof(NotifyMonsterTakeDamage), data[70]},
            {typeof(NotifyMonsterDie), data[71]},
            {typeof(NQuaternion), data[72]},
            {typeof(NSyncMonster), data[73]},
            {typeof(NotifyMonsterRepMovement), data[74]},
            {typeof(NotifyMonsterPlayAction), data[75]},
            {typeof(ReqStartQuest), data[76]},
            {typeof(RspStartQuest), data[77]},
            {typeof(ReqUpgradeDisc), data[78]},
            {typeof(RspUpgradeDisc), data[79]},
            {typeof(MsgGatherMaterial), data[80]},
            {typeof(MsgCompleteQuestChain), data[81]},
            {typeof(NotifyObtainItems), data[82]},
        };
    }
}