
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.main
{

public sealed partial class DiscConfig : Luban.BeanBase
{
    public DiscConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Rank = (string)_obj.GetValue("rank");
        IconLoc = (string)_obj.GetValue("icon_loc");
        { var __json0 = _obj.GetValue("set_abilities_2"); SetAbilities2 = new System.Collections.Generic.List<main.AbilityConfig>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.AbilityConfig __v0;  __v0 = main.AbilityConfig.DeserializeAbilityConfig(__e0);  SetAbilities2.Add(__v0); }   }
        { var __json0 = _obj.GetValue("set_abilities_4"); SetAbilities4 = new System.Collections.Generic.List<main.AbilityConfig>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { main.AbilityConfig __v0;  __v0 = main.AbilityConfig.DeserializeAbilityConfig(__e0);  SetAbilities4.Add(__v0); }   }
        SetEffect2Desc = (string)_obj.GetValue("set_effect_2_desc");
        SetEffect4Desc = (string)_obj.GetValue("set_effect_4_desc");
        Desc = (string)_obj.GetValue("desc");
    }

    public static DiscConfig DeserializeDiscConfig(JToken _buf)
    {
        return new main.DiscConfig(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string Rank;
    public readonly string IconLoc;
    public readonly System.Collections.Generic.List<main.AbilityConfig> SetAbilities2;
    public readonly System.Collections.Generic.List<main.AbilityConfig> SetAbilities4;
    public readonly string SetEffect2Desc;
    public readonly string SetEffect4Desc;
    public readonly string Desc;


    public const int __ID__ = 101224620;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SetAbilities2) { _e?.ResolveRef(tables); }
        foreach (var _e in SetAbilities4) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "rank:" + Rank + ","
        + "iconLoc:" + IconLoc + ","
        + "setAbilities2:" + Luban.StringUtil.CollectionToString(SetAbilities2) + ","
        + "setAbilities4:" + Luban.StringUtil.CollectionToString(SetAbilities4) + ","
        + "setEffect2Desc:" + SetEffect2Desc + ","
        + "setEffect4Desc:" + SetEffect4Desc + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

